
package examen.pkg1.eduardoespinoza;


import static examen.pkg1.eduardoespinoza.Clientes.Cantidad_Preferenciales;
import static examen.pkg1.eduardoespinoza.Clientes.Cantidad_SolNS;
import static examen.pkg1.eduardoespinoza.Clientes.Cantidad_SombraEO;

import javax.swing.JTextField;

/**
 *
 * @author Eduardo
 */
public class Consultar_Factura extends javax.swing.JFrame {


    public Consultar_Factura() {
        initComponents();
        this.setSize(840, 450);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Revelar = new javax.swing.JButton();
        DATOSSOL = new javax.swing.JTextField();
        DATOSPREFERENCIAL = new javax.swing.JTextField();
        DATOSSOMBRA = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Revelar.setBackground(new java.awt.Color(204, 255, 204));
        Revelar.setText("Entradas");
        Revelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevelarActionPerformed(evt);
            }
        });

        DATOSSOL.setBackground(new java.awt.Color(255, 255, 204));

        DATOSPREFERENCIAL.setBackground(new java.awt.Color(204, 255, 255));

        DATOSSOMBRA.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DATOSPREFERENCIAL, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(DATOSSOMBRA)
                            .addComponent(DATOSSOL)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(Revelar)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(Revelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DATOSSOL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(DATOSSOMBRA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(DATOSPREFERENCIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RevelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevelarActionPerformed
 //Por medio del #factura, se motrara la cantidad de clientes que optaron por comprar en cierta localidad
      DATOSSOL.setText("Clientes que compraron en SOL: "+String.valueOf(Cantidad_SolNS));
      DATOSSOMBRA.setText("Clientes que compraron en SOMBRA: "+String.valueOf(Cantidad_SombraEO));  
      DATOSPREFERENCIAL.setText("Clientes que compraron en PREFERENCIALES: "+String.valueOf(Cantidad_Preferenciales));  
        
    }//GEN-LAST:event_RevelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    Consultar_Factura frame=new Consultar_Factura();
    frame.setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar_Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DATOSPREFERENCIAL;
    private javax.swing.JTextField DATOSSOL;
    private javax.swing.JTextField DATOSSOMBRA;
    public javax.swing.JButton Revelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
